### ISSUE TITLE
Mobile size layout

### ISSUE THREAD

**Issue by dkastl** [consento-org/consento-website#12]
The mobile layout has a few issues, mostly spacing. The following screenshot shows a few and I added comments in red. But this might not be all as the screenshot ends in the middle.

In general the mobile view has problems with:

- [x] Spacing is often not right and it even appears sometimes that content belongs to the wrong picture or headline. Make blocks visually belong together.

- [x] When columns collapse into one, sometimes pictures show before the headline. You can fix the order with this: https://getbootstrap.com/docs/4.1/utilities/flex/#order

![capture_Pixel_2](https://user-images.githubusercontent.com/227762/73594136-9c48be00-454e-11ea-8f8a-1f39015f836b.png)

**Comment by Torgian** [comment]
I've been working on this, and I think I will have to spend a bit more time to get it to look _just_ right. At the moment, I have images showing up on the bottom of each section, and I also plan to add a light background color to give some separation between blocks. 

However, due to the spacing issues, I need to spend a bit extra time to change some things since some of spacing classes don't work well with `flex`.

**Comment by marcchataigner-zz** [comment]
@Torgian I quickly tried to set up a mobile version in Zeplin, would that hep?

https://zpl.io/VxXe8QR

**Comment by Torgian** [comment]
Please wait. I am finishing up what I currently made and will put it on the server soon. It includes some spacing fixes as well.

**Comment by Torgian** [comment]
This is finished.

**Comment by Torgian** [comment]
I've done quite a lot of changes tonight, so please double check.

**Comment by Torgian** [comment]
I am closing this since mobile seems to be ok now. Please reopen and comment if something else's found.
