### ISSUE TITLE
Lines of codes in 'our technology' section

### ISSUE THREAD

**Issue by marcchataigner-zz** [consento-org/consento-website#17]
@martinheidegger The idea was to display some cool lines of codes here, to show off a bit.  :-)   For non-technical people like me, it looks like complicated and serious. For expert people, it might be reassuring to have a sneak peak on 1 key property of the code. Like encryption protocol? Or shamir secret? ...  Would you have an idea?

ex: 

- https://www.vaultproject.io

**Comment by martinheidegger** [comment]
The code displayed at `vaultproject` is actually functioning code that can be copy & pasted which makes it accessible & awesome by design.

We do not have an API or simple thing that can be used out of the box. This will - at best - fool a non-tech person.

This might be a string you are looking for, but I suggest to work on the concept:

https://github.com/consento-org/crypto/blob/f61fbdec78f1ca271293a8d076488b56c2aee734/src/handshake/index.ts#L46-L65

_Note: There are many issues in this repo, please assign me to issues, else I tend to ignore them_

<img width="220" alt="Screen Shot 2020-02-05 at 01 22 38" src="https://user-images.githubusercontent.com/914122/73764272-04e5a400-47b6-11ea-8c44-5460b9b1c259.png">

**Comment by marcchataigner-zz** [comment]
Thx.   :-)

**Comment by marcchataigner-zz** [comment]
@Torgian for the 'technology' part, the box where to display some cool lines of code.  :-)

```
    confirm (accept: IHandshakeAcceptMessage): ICancelable<IHandshakeConfirmation> {
      return cancelable<IHandshakeConfirmation, HandshakeInit>(function * () {
        const secretKey = (yield crypto.computeSecret(this.confirmKey, Buffer.from(accept.token, 'base64'))) as Uint8Array
        const bob = (yield createSender()) as ISender
        const sendKey = (yield crypto.decrypt(secretKey, Buffer.from(accept.secret, 'base64'))) as IEncodable
        if (!(sendKey instanceof Uint8Array)) {
          throw Object.assign(new Error('Expected buffer in decrypted message'), { code: 'invalid-message' })
        }
        const sender = (yield createSenderFromSendKey(sendKey)) as ISender
        return yield new HandshakeConfirmation({
          connection: new Connection({
            sender,
            receiver: bob.newReceiver()
          }),
          // In case you are wondering why we not just simply return "bob" as sender
          // but instead pass it in two messages: the reason is that without this step
          finalMessage: bob.sendKey
        })
      }, this)
    }
```

**Comment by Torgian** [comment]
I've added this code block. Due to the nature of the `<code>` tag, it will still scroll horizontally.
