### ISSUE TITLE
center value section

### ISSUE THREAD

**Issue by marcchataigner-zz** [consento-org/consento-website#18]
If it is possible, center the 2nd line of the value section.

![Screen Shot 2020-02-03 at 12 09 27](https://user-images.githubusercontent.com/3974900/73622859-0f048700-467e-11ea-9fcb-6b4c4788fb3d.png)

**Comment by Torgian** [comment]
I don't actually understand what you mean by centering the second line.

The problem with this is that there are only five icons. The bottom row can either be left aligned, centered, or right aligned. The other option is to change the styling overall: 2x2x1, with the last row being centered. 

Or, we can make them all smaller on larger desktop mode, and have all five in a single row. 

There are a few ways we can try to fix this, but I think it might look a bit awkward since we only have the five icons.

**Comment by martinheidegger** [comment]
@marcchataigner Please always submit a _is_ and _want_ screen as it is hard to keep track of which version you are talking about _(many updates)_ and what issue you are seeing.

Currently it looks in firefox like ↓ for me and here the second line is centered pretty much like you requested.

<img width="600" alt="Screen Shot 2020-02-05 at 01 18 30" src="https://user-images.githubusercontent.com/914122/73763942-8557d500-47b5-11ea-980f-c860fae35b13.png">

**Comment by marcchataigner-zz** [comment]
@martinheidegger Nathaniel already did the update, that's why.  :-)   He's quick

**Comment by martinheidegger** [comment]
@marcchataigner so this is fixed?
