### ISSUE TITLE
Mixing of Credits and Supporters?

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#49]
@marcchataigner The credits page was originally designed to have a space crediting the open source tools that we used for making this page. Why do we put the supporters there?

**Comment by Torgian** [comment]
This is behavior I need to fix on `pages.hbs` with a conditional statement. 

Note: As for About, Team, Supporter pages, since they are pages created from within the Ghost page creator, I actually don’t have these pages locally, which makes it difficult to test styles for these pages.  Is there a datafile I can download from the write.georepublic.net <http://write.georepublic.net/> page so I can get these pages?

**Comment by martinheidegger** [comment]
It is possible to export/import the data to/from a ghost instance from the admin interface:

<img width="180" alt="Screen Shot 2020-02-05 at 22 07 38" src="https://user-images.githubusercontent.com/914122/73844496-05d50f00-4864-11ea-9d33-12314a2a6e6c.png">

⬇︎

<img width="655" alt="Screen Shot 2020-02-05 at 22 08 10" src="https://user-images.githubusercontent.com/914122/73844537-184f4880-4864-11ea-82f0-abb9056e5a13.png">

**Comment by marcchataigner-zz** [comment]
@martinheidegger yes, you're right, let's the credits page only with credits + hosting. 

Skip the `thy support us` block

**Comment by Torgian** [comment]
To clarify, you want to remove this section ( They Trust Us ), from the Credits page,  correct?

<img width="785" alt="Screen Shot 2020-02-18 at 9 36 43 AM" src="https://user-images.githubusercontent.com/8596793/74696352-3b013a00-5232-11ea-9433-c340503e4243.png">

**Comment by Torgian** [comment]
Refer [4d367d2](https://github.com/consento-org/consento-website/commit/4d367d2b04ee22648124e988efab3e379da5435a)

Removed supporters block from credits page.

<img width="1018" alt="Screen Shot 2020-02-20 at 2 33 19 PM" src="https://user-images.githubusercontent.com/8596793/74907250-f9b58980-53ed-11ea-9226-c12332c0f319.png">
