### ISSUE TITLE
Team member display broken

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/consento-website#79]
The team member display cuts off the top of avatars and the icons are red

<img width="1190" alt="Screen Shot 2020-02-26 at 14 39 54" src="https://user-images.githubusercontent.com/914122/75315381-f9156b00-58a5-11ea-965f-0edeeca765f1.png">

**Comment by Torgian** [comment]
[Commit b15c606](https://github.com/consento-org/consento-website/commit/b15c606efcfb657687059f8ca19015cde52d554e)

<img width="1352" alt="Screen Shot 2020-02-26 at 4 08 37 PM" src="https://user-images.githubusercontent.com/8596793/75324636-5adbd200-58b2-11ea-8f95-5aed332e57f1.png">

**Comment by Torgian** [comment]
I changed the colors of the icons and hover color as well in https://github.com/consento-org/consento-website/commit/c4230c1d2165802bc57b4088990ab77ea99225db. However, since there is no design for this, @marcchataigner @Tannybunny are these colors ok?

``` 
icon color #9fa3a6;
hover color #18bfef
```

<img width="1098" alt="Screen Shot 2020-02-26 at 4 43 55 PM" src="https://user-images.githubusercontent.com/8596793/75327355-38988300-58b7-11ea-9e50-0d2d8725b37a.png">

**Comment by Torgian** [comment]
<img width="226" alt="Screen Shot 2020-02-26 at 4 46 41 PM" src="https://user-images.githubusercontent.com/8596793/75327569-962ccf80-58b7-11ea-9bec-466abf252746.png">

**Comment by martinheidegger** [comment]
The underline is a bit irking & also, why this color? I havn't seen it anywhere else?! Is `fg-link` used for links in the _foreground_?

**Comment by Torgian** [comment]
There are no other colors for the icons, other than a white color with an opacity that is being used in the footer. I have not seen a color to be used for these icons, so I thought a gray color would be nice, since it somewhat matches the footer icon colors. 

@marcchataigner when you get a chance, please let us know of a good color to choose. Or @martinheidegger feel free to let me know which color you like best.

**Comment by marcchataigner-zz** [comment]
@Torgian nice, I like the grey. @martinheidegger 's cap looks outstanding.   :-D   

Did you try perhaps with the consento light blue or light magenta? 

As for me, this nice warm grey works for me.   :-)

**Comment by Torgian** [comment]
[Commit](https://github.com/consento-org/consento-website/commit/44f5b0aa1faa0de99ce04d5b556bb6de431cd457
<img width="301" alt="Screen Shot 2020-02-26 at 9 30 09 PM" src="https://user-images.githubusercontent.com/8596793/75349197-47932b80-58df-11ea-9b41-95709bc92666.png">
)
