### ISSUE TITLE
Mobile view front page 

### ISSUE THREAD

**Issue by Tannybunny** [consento-org/consento-website#98]
I think the current view when opening the consento mobile view is not so great at the moment.
I dont know if it's possible to define other H1 settings for the mobile view, if it's possible I'd suggest making the font a lot smaller , like  in the attached picture. Also if possible not cut the illustration , maybe make it smaller.

![Screenshot_20200303-120513 copy](https://user-images.githubusercontent.com/51223963/75750720-23fd3480-5d68-11ea-9aca-f1e4e31b9391.png)

**Comment by Torgian** [comment]
@Tannybunny I have modified this. I have also changed the font size for the other heading titles to match better with the sizing you requested, so please review. Here are a couple of screenshots of the landing page.

iPhone 5, 6, 6+ sizes following.

<img width="320" alt="Screen Shot 2020-03-04 at 12 15 25 PM" src="https://user-images.githubusercontent.com/8596793/75845082-f5886380-5e12-11ea-98e5-a76f442fa5bd.png">
<img width="323" alt="Screen Shot 2020-03-04 at 12 11 55 PM" src="https://user-images.githubusercontent.com/8596793/75845077-f28d7300-5e12-11ea-8951-76e1b5f8970a.png">
<img width="414" alt="Screen Shot 2020-03-04 at 12 22 09 PM" src="https://user-images.githubusercontent.com/8596793/75845086-f620fa00-5e12-11ea-8575-cde77271b8d5.png">

**Comment by Torgian** [comment]
Please refer to commit https://github.com/consento-org/consento-website/commit/3ecc790aa72a94ec851e6a9216bbe17315fed28d

I had to adjust image media queries a bit for spacing and sizing due to the changes in the h1 text element, especially for larger screens. Screen:


<img width="871" alt="Screen Shot 2020-03-04 at 1 13 44 PM" src="https://user-images.githubusercontent.com/8596793/75847460-38016e80-5e1a-11ea-9367-380be08bef07.png">

**Comment by Tannybunny** [comment]
looks good on mobile but maybe now on desktop the top page illustration and text are a bit too close to the navigation? 🙈
